services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/galgobet
      - JWT_SECRET=galgobet_secreto_super_seguro_2026
      - JWT_EXPIRES_IN=24h
      - CREDITOS_INICIALES=500
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
